import { createTheme } from "@material-ui/core/styles";

export const theme = createTheme({
  typography: {
    fontFamily: "Roboto",
    h1: {
      fontStyle: "normal",
      fontWeight: 500,
      fontSize: "20px",
      color: "#555",
      lineHeight: "125%",
    },
    h2: {
      fontStyle: "normal",
      fontWeight: 400,
      fontSize: "14px",
      color: "#fff",
      lineHeight: "125%",
    },
    h3: {
      fontStyle: "normal",
      fontWeight: 400,
      fontSize: "13px",
      color: "#fff",
      lineHeight: "125%",
    },
    h4: {
      fontStyle: "normal",
      fontWeight: 400,
      fontSize: "14px",
      color: "rgba(0,0,0,.87)",
      lineHeight: "125%",
    },
    h5: {
      fontStyle: "normal",
      fontWeight: 400,
      fontSize: "14px",
      color: "#ff4d2d",
      lineHeight: "125%",
    },
    h6: {
      fontStyle: "normal",
      fontWeight: 400,
      fontSize: "16px",
      color: "rgba(0,0,0,.87)",
      lineHeight: "125%",
    },
    subtitle1: {
      fontStyle: "normal",
      fontWeight: 500,
      fontSize: "17px",
      color: "#d0011b",
      lineHeight: "100%",
    },
    subtitle2: {
      fontStyle: "normal",
      fontWeight: 500,
      fontSize: "24px",
      color: "#222",
      lineHeight: "125%",
    },
    caption: {
      fontStyle: "normal",
      fontWeight: 600,
      fontSize: "18px",
      color: "rgba(0,0,0,.87)",
      lineHeight: "125%",
      textTransform: "uppercase",
    },
    body2: {
      fontStyle: "normal",
      fontWeight: 400,
      fontSize: "12px",
      color: "rgba(0,0,0,.87)",
      lineHeight: "125%",
    },
    body1: {
      fontStyle: "normal",
      fontWeight: 300,
      fontSize: "12px",
      color: "rgba(0,0,0,.5)",
      lineHeight: "125%",
    },
    overline: {
      fontStyle: "normal",
      fontWeight: 500,
      fontSize: "20px",
      color: "#fff",
      lineHeight: "125%",
    },
  },
  palette: {},
});
