export const GET_BRAND_REQUEST = "GET_BRAND_REQUEST";
export const GET_BRAND_SUCCESS = "GET_BRAND_SUCCESS";
export const GET_BRAND_FAILURE = "GET_BRAND_FAILURE";

export const GET_BRAND_PRODUCT_REQUEST = "GET_BRAND_PRODUCT_REQUEST";
export const GET_BRAND_PRODUCT_SUCCESS = "GET_BRAND_PRODUCT_SUCCESS";
export const GET_BRAND_PRODUCT_FAILURE = "GET_BRAND_PRODUCT_FAILURE";
