export const GET_BRAND_REQUEST = "GET_BRAND_REQUEST";
export const GET_BRAND_SUCCESS = "GET_BRAND_SUCCESS";
export const GET_BRAND_FAILURE = "GET_BRAND_FAILURE";

export const GET_TYPE_REQUEST = "GET_TYPE_REQUEST";
export const GET_TYPE_SUCCESS = "GET_TYPE_SUCCESS";
export const GET_TYPE_FAILURE = "GET_TYPE_FAILURE";

export const GET_LIST_PRODUCT_REQUEST = "GET_LIST_PRODUCT_REQUEST";
export const GET_LIST_PRODUCT_SUCCESS = "GET_LIST_PRODUCT_SUCCESS";
export const GET_LIST_PRODUCT_FAILURE = "GET_LIST_PRODUCT_FAILURE";

export const GET_FILTER_PRODUCT_REQUEST = "GET_FILTER_PRODUCT_REQUEST";
export const GET_FILTER_PRODUCT_SUCCESS = "GET_FILTER_PRODUCT_SUCCESS";
export const GET_FILTER_PRODUCT_FAILURE = "GET_FILTER_PRODUCT_FAILURE";

export const GET_DETAIL_PRODUCT_REQUEST = "GET_DETAIL_PRODUCT_REQUEST";
export const GET_DETAIL_PRODUCT_SUCCESS = "GET_DETAIL_PRODUCT_SUCCESS";
export const GET_DETAIL_PRODUCT_FAILURE = "GET_DETAIL_PRODUCT_FAILURE";
