export const GET_LIST_PRODUCT_REQUEST = "GET_LIST_PRODUCT_REQUEST";
export const GET_LIST_PRODUCT_SUCCESS = "GET_LIST_PRODUCT_SUCCESS";
export const GET_LIST_PRODUCT_FAILURE = "GET_LIST_PRODUCT_FAILURE";

export const GET_FILTER_PRODUCT_REQUEST = "GET_FILTER_PRODUCT_REQUEST";
export const GET_FILTER_PRODUCT_SUCCESS = "GET_FILTER_PRODUCT_SUCCESS";
export const GET_FILTER_PRODUCT_FAILURE = "GET_FILTER_PRODUCT_FAILURE";

export const GET_DETAIL_PRODUCT_REQUEST = "GET_DETAIL_PRODUCT_REQUEST";
export const GET_DETAIL_PRODUCT_SUCCESS = "GET_DETAIL_PRODUCT_SUCCESS";
export const GET_DETAIL_PRODUCT_FAILURE = "GET_DETAIL_PRODUCT_FAILURE";
