export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILED = "USER_LOGIN_FAILED";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAILED = "USER_REGISTER_FAILED";

export const USER_LOGOUT = "USER_LOGOUT";

export const USER_GET_ADDRESS = "USER_GET_ADDRESS";
export const USER_GET_ONE_ADDRESS = "USER_GET_ONE_ADDRESS";
export const USER_ADD_ADDRESS = "USER_ADD_ADDRESS";
export const USER_UPDATE_ADDRESS = "USER_UPDATE_ADDRESS";
export const USER_REMOVE_ADDRESS = "USER_REMOVE_ADDRESS";
