export const GET_TYPE_REQUEST = "GET_TYPE_REQUEST";
export const GET_TYPE_SUCCESS = "GET_TYPE_SUCCESS";
export const GET_TYPE_FAILURE = "GET_TYPE_FAILURE";

export const GET_TYPE_BRAND_REQUEST = "GET_TYPE_BRAND_REQUEST";
export const GET_TYPE_BRAND_SUCCESS = "GET_TYPE_BRAND_SUCCESS";
export const GET_TYPE_BRAND_FAILURE = "GET_TYPE_BRAND_FAILURE";
