export const POST_REVIEW = "POST_REVIEW";
export const GET_REVIEW = "GET_REVIEW";
export const UPDATE_REVIEW = "UPDATE_REVIEW";
export const REMOVE_REVIEW = "REMOVE_REVIEW";
export const GET_STATIC = "GET_STATIC";
export const FILTER_BY_STAR = "FILTER_BY_STAR";
export const FILTER_BY_IMAGE_OR_VIDEO = "FILTER_BY_IMAGE_OR_VIDEO";
